### ISSUE TITLE
Descend into directories?

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-uploader#2]
It's terrific being able to upload a whole directory of images, but would it be a good idea to also recurse into subdirectories of the specified directory?

I might have a go at building such a feature.

**Comment by TheFox** [comment]
This is a good idea. You can use [Symfony Finder](https://packagist.org/packages/symfony/finder) to collect all files for upload.

**Comment by samwilson** [comment]
You're so quick! :-) Thank you very much, this is working very well.
