### ISSUE TITLE
Re-implement move-after-uploaded

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-uploader#5]
The old feature of moving files after they were uploaded was great, especially from the point of view of having to stop uploads halfway through — it meant that one could resume, with the same command, and be assured of not re-uploading anything.

Of course, there's a bigger issue here of how to prevent duplicates being uploaded. I think some people have gotten around that by creating their own checksum tags e.g. `md5sum:b66a82cd69b0d71c2ea4f5dce28a7f40` on each photo, and then comparing that at upload time. It does seem crazy that Flickr don't provide such a thing in their API!

But yes, for the time being I think the move option is good.

**Comment by TheFox** [comment]
I wasn't sure if this was a good idea at all, so I removed it in v2. I will re-implement it in v2.1.

**Comment by samwilson** [comment]
I guess this issue can be postponed and readded to [TheFox/flickr-cli](https://github.com/TheFox/flickr-cli), when that's up and running?

**Comment by TheFox** [comment]
Moved to TheFox/flickr-cli#3.
