### ISSUE TITLE
Recommend downloader?

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-uploader#6]
@TheFox have you written, or do you have a recommendation for, a Flickr downloader? Something that can be used to backup all that one has uploaded?

I'm only adding this as an issue here because if you do have a preferred one, it might be nice to add a note in the README here. :-)

Lots of the ones I've seen are nowhere near as professional as your code!

**Comment by TheFox** [comment]
I have written a downloader as well: <https://github.com/TheFox/flickr-downloader>

But it would be better to merge both projects and name it `flickr-cli`.

In detail:

- Rename TheFox/flickr-uploader to TheFox/flickr-cli.
- Move code from TheFox/flickr-downloader to TheFox/flickr-uploader as a separate [command](https://github.com/TheFox/flickr-uploader/tree/1b3fa4f53e0010923a3d6c041bb78b4144a4ff1c/src/TheFox/FlickrUploader/Command).
- Deprecate TheFox/flickr-downloader. Link to TheFox/flickr-cli.

What do you think?

**Comment by samwilson** [comment]
That sounds very sensible. Would de-duplicate a fair bit of code, I'd imagine?

It'd be a wonderful utility, to have all in one.

Let me know if I can help with anything. :-)

**Comment by TheFox** [comment]
I guess we can de-duplicate code.

It would be cool if you could test flickr-cli and write a blog post re-view about it after I released v1.0.0. :) And of course pull requests are always welcome, for example to de-duplicate code. I want to start coding the project in the next days.

**Comment by samwilson** [comment]
Will do! :-) (I'm watching the new repo now too.)

Thanks so much for working on this. It's great!

**Comment by samwilson** [comment]
Oh and the de-duplication I meant was just e.g. the need to only have one 'auth' command. :-)
